name: dqlab_idc3
dependencies:
  - python=3.7.4
  - pandas=0.25.1
  - numpy=1.17.2
  - mysql-connector-python=8.0.18
  - bokeh=1.3.4
  - ipython=7.8.0
  - jupyter=1.0.0
  - notebook=6.0.1
  - nodejs=10.13.0
